// <auto-generated />
using KreamornLoanTrakerAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KreamornLoanTrakerAPI.Migrations
{
    [DbContext(typeof(PersonalDetailContext))]
    [Migration("20240404093710_First Migration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KreamornLoanTrakerAPI.Models.AdminDetail", b =>
                {
                    b.Property<int>("AdminDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminDetailId"));

                    b.Property<string>("EcNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AdminDetailId");

                    b.ToTable("AdminDetails");
                });

            modelBuilder.Entity("KreamornLoanTrakerAPI.Models.LoanDetail", b =>
                {
                    b.Property<int>("LoanDeatailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanDeatailId"));

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Approved")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("ContactInformation")
                        .HasColumnType("varbinary(MAX)");

                    b.Property<byte[]>("DeclinationLetter")
                        .HasColumnType("varbinary(MAX)");

                    b.Property<byte[]>("DisclosureStatements")
                        .HasColumnType("varbinary(MAX)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("LoanApprovalLetter")
                        .HasColumnType("varbinary(MAX)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RepaymentSchedule")
                        .HasColumnType("varbinary(MAX)");

                    b.HasKey("LoanDeatailId");

                    b.ToTable("LoanDetails");
                });

            modelBuilder.Entity("KreamornLoanTrakerAPI.Models.PersonalDetail", b =>
                {
                    b.Property<int>("PersonalDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonalDetailId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AnnualSalary")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("BankStatement")
                        .HasColumnType("varbinary(MAX)");

                    b.Property<string>("Benefit")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("BenefitDocument")
                        .HasColumnType("varbinary(MAX)");

                    b.Property<byte[]>("CollateralDocument")
                        .HasColumnType("varbinary(MAX)");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Employer")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("EmploymentVerification")
                        .HasColumnType("varbinary(MAX)");

                    b.Property<string>("Expense")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LoanAmount")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoanTenure")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MonthlyIncome")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("OtherDocument")
                        .HasColumnType("varbinary(MAX)");

                    b.Property<string>("PersonalPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("ProofOfIdentity")
                        .HasColumnType("varbinary(MAX)");

                    b.Property<byte[]>("ProofOfIncome")
                        .HasColumnType("varbinary(MAX)");

                    b.Property<byte[]>("ProofOfResidence")
                        .HasColumnType("varbinary(MAX)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WageFrequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WorkNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PersonalDetailId");

                    b.ToTable("PersonalDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
