// <auto-generated />
using KreamornLoanTrakerAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KreamornLoanTrakerAPI.Migrations
{
    [DbContext(typeof(PersonalDetailContext))]
    partial class PersonalDetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KreamornLoanTrakerAPI.Models.LoanDetail", b =>
                {
                    b.Property<int>("LoanDeatailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanDeatailId"));

                    b.Property<byte[]>("ContactInformation")
                        .IsRequired()
                        .HasColumnType("varbinary(MAX)");

                    b.Property<byte[]>("DisclosureStatements")
                        .IsRequired()
                        .HasColumnType("varbinary(MAX)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<byte[]>("LoanApprovalLetter")
                        .IsRequired()
                        .HasColumnType("varbinary(MAX)");

                    b.Property<byte[]>("RepaymentSchedule")
                        .IsRequired()
                        .HasColumnType("varbinary(MAX)");

                    b.HasKey("LoanDeatailId");

                    b.ToTable("LoanDetails");
                });

            modelBuilder.Entity("KreamornLoanTrakerAPI.Models.PersonalDetail", b =>
                {
                    b.Property<int>("PersonalDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonalDetailId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AnnualSalary")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("BankStatement")
                        .IsRequired()
                        .HasColumnType("varbinary(MAX)");

                    b.Property<string>("Benefit")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("BenefitDocument")
                        .HasColumnType("varbinary(MAX)");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Employer")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Expense")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MonthlyIncome")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PersonalPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("ProofOfAddress")
                        .IsRequired()
                        .HasColumnType("varbinary(MAX)");

                    b.Property<byte[]>("ProofOfIdentity")
                        .IsRequired()
                        .HasColumnType("varbinary(MAX)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WageFrequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WorkNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PersonalDetailId");

                    b.HasIndex("Id");

                    b.ToTable("PersonalDetails");
                });

            modelBuilder.Entity("KreamornLoanTrakerAPI.Models.PersonalDetail", b =>
                {
                    b.HasOne("KreamornLoanTrakerAPI.Models.LoanDetail", "LoanDetail")
                        .WithMany("PersonalDetails")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanDetail");
                });

            modelBuilder.Entity("KreamornLoanTrakerAPI.Models.LoanDetail", b =>
                {
                    b.Navigation("PersonalDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
